services:

  db:
    container_name : pennypincher_db
    image: postgres:18
    restart: always
    user: postgres
    secrets:
      - db-password
    volumes:
      - pennypincher-postgres-data:/var/lib/postgresql/
      - ../pennypincherdb.sql:/docker-entrypoint-initdb.d/pennypincherdb.sql:ro
    environment:
      # - POSTGRES_DB=penny_pincher_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  pennypincher-postgres-data:
secrets:
  db-password:
    file: ./dbpassword.txt